const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let notes=JSON.parse(localStorage.getItem('cn4-notes')||'[]'),draftAttachments=[];
const toast=t=>{let e=$('#toast');e.textContent='✓ '+t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};
function stars(){let box=$('#stars');box.innerHTML='';for(let i=0;i<75;i++){let s=document.createElement('i');s.className='star';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*55+'%';s.style.setProperty('--s',(1+Math.random()*3)+'px');s.style.setProperty('--o',(.35+Math.random()*.65));s.style.setProperty('--d',(1.5+Math.random()*4)+'s');box.appendChild(s)}}stars();
function go(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.go===id));if(id==='ai')makePrompt();if(id==='archive')renderArchive();if(id==='home')renderRecent();scrollTo(0,0)}$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function current(){return {id:crypto.randomUUID?.()||Date.now()+'',subject:$('#subject').value.trim(),session:$('#sessionNumber').value||'1',title:$('#title').value.trim(),date:$('#date').value,notes:$('#notes').value.trim(),attachments:draftAttachments,aiResult:$('#aiResult').value.trim()}}
function renderAttachments(){let a=$('#attachmentList');a.innerHTML=draftAttachments.map((x,i)=>`<div class="attachment"><span>📎 ${x.name}</span><button data-rm="${i}">×</button></div>`).join('')||'<small>هنوز فایلی اضافه نشده.</small>';$$('[data-rm]').forEach(b=>b.onclick=()=>{draftAttachments.splice(+b.dataset.rm,1);renderAttachments()})}
$('#fileInput').onchange=e=>{[...e.target.files].forEach(f=>draftAttachments.push({name:f.name,type:f.type,size:f.size}));renderAttachments();toast('فایل اضافه شد')};
$('#saveBtn').onclick=()=>{let n=current();if(!n.subject&&!n.notes)return toast('حداقل درس یا نکات را وارد کن');notes.unshift(n);localStorage.setItem('cn4-notes',JSON.stringify(notes));$('#saveState').textContent='ذخیره شد';toast('جلسه ذخیره شد');renderRecent()};
$('#clearBtn').onclick=()=>{['subject','title','notes','aiResult'].forEach(id=>$('#'+id).value='');draftAttachments=[];renderAttachments();toast('پاک شد')};
function card(n){return `<article class="glass note-item"><h3>${n.subject||'بدون درس'} — جلسه ${n.session}</h3><p>${n.title||'بدون عنوان'} • ${n.date||''}</p><p>${(n.notes||'').slice(0,95)}${n.notes?.length>95?'…':''}</p>${n.attachments?.length?`<p>📎 ${n.attachments.length} پیوست</p>`:''}</article>`}
function renderRecent(){$('#recent').innerHTML=notes.slice(0,4).map(card).join('')||'<p>هنوز جلسه‌ای ذخیره نشده.</p>'}function renderArchive(){let q=$('#searchNotes').value.toLowerCase();$('#archiveList').innerHTML=notes.filter(n=>(n.subject+n.title+n.notes).toLowerCase().includes(q)).map(card).join('')||'<p>نتیجه‌ای نیست.</p>'}$('#searchNotes').oninput=renderArchive;
function makePrompt(){let mode=$('#promptMode').value;$('#prompt').value=`نقش یک دستیار آموزشی دقیق را داشته باش.\nنوع خروجی: ${mode}\nدرس: ${$('#subject').value||'نامشخص'}\nجلسه شماره: ${$('#sessionNumber').value||'1'}\nعنوان: ${$('#title').value||'بدون عنوان'}\n\nنکات کاربر:\n${$('#notes').value||'هنوز نکاتی وارد نشده'}\n\nبر اساس نکات کاربر، خروجی را منظم، دقیق و مناسب مطالعه تولید کن.`}$('#promptMode').onchange=makePrompt;
$('#copyPrompt').onclick=async()=>{try{await navigator.clipboard.writeText($('#prompt').value);toast('پرامپت کپی شد')}catch{toast('اجازه کلیپ‌بورد داده نشد')}};$$('.aiopen').forEach(b=>b.onclick=()=>{navigator.clipboard?.writeText($('#prompt').value);window.open(b.dataset.url,'_blank');toast('پرامپت کپی و AI باز شد')});
$('#pasteResult').onclick=async()=>{try{$('#aiResult').value=await navigator.clipboard.readText();toast('نتیجه Paste شد')}catch{toast('دسترسی کلیپ‌بورد ممکن نیست')}};$('#saveResult').onclick=()=>{localStorage.setItem('cn4-ai-result',$('#aiResult').value);toast('نتیجه ذخیره شد')};$('#aiResult').value=localStorage.getItem('cn4-ai-result')||'';
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');$('#themeBtn').textContent=document.body.classList.contains('dark')?'🌙':'☀️';localStorage.setItem('cn4-dark',document.body.classList.contains('dark'))};if(localStorage.getItem('cn4-dark')==='true'){$('#themeBtn').click()}
$('#themeSelect').onchange=e=>{document.body.classList.toggle('dark',e.target.value==='dark'||(e.target.value==='system'&&matchMedia('(prefers-color-scheme:dark)').matches));};$('#accent').onchange=e=>{document.body.classList.remove('blue','purple');if(e.target.value!=='green')document.body.classList.add(e.target.value)};
$('#exportAll').onclick=()=>{let t=notes.map(n=>`# ${n.subject} — جلسه ${n.session}\n## ${n.title}\n${n.notes}`).join('\n\n---\n\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:'text/markdown'}));a.download='class-notes.md';a.click()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');renderRecent();renderAttachments();$('#date').value=new Date().toISOString().slice(0,10);
